### ISSUE TITLE
Fails on local files

### ISSUE THREAD

**Issue by timpulver** [sidorares/crconsole#14]
When using `crconsole` with a local file `file:///Users/me/index.html` I get an error:

    "Parameter 'url' must be a string, not " + typeof url

**Comment by timpulver** [comment]
Does not work with a local server (python) on `http://localhost:8000/` either:
    "Parameter 'url' must be a string, not " + typeof url

**Comment by timpulver** [comment]
Nevermind, it was a problem in the `url`-package. Just updated Node and everything works fine!

**Comment by sidorares** [comment]
oh, great :)
