### ISSUE TITLE
Debugger syntax highlight for white background

### ISSUE THREAD

**Issue by felippenardi** [sidorares/crconsole#19]
I noticed that syntax highlight is bit broken on white background screens:

<img width="596" alt="screen shot 2016-03-08 at 8 54 29 pm" src="https://cloud.githubusercontent.com/assets/1354492/13620689/5128bfde-e570-11e5-8c6e-983cb3031bce.png">

Is there a way to set the fonts without a color use the default font color?

**Comment by sidorares** [comment]
Hi! I'm using [cardinal](https://www.npmjs.com/package/cardinal) for highlight

You can change theme by editing ~/.cardinalrc file - see https://www.npmjs.com/package/cardinal#theme

**Comment by sidorares** [comment]
maybe worth filling issue at https://github.com/thlorenz/cardinal/issues

**Comment by felippenardi** [comment]
@sidorares Editing `~/.cardinalrc` solved the problem perfectly! Thank you so much :)
